#!/bin/sh
ROOT_POOL=rpool
LOFIDEVICE=/dev/lofi/100

sudo /usr/sbin/lofiadm -c aes-256-cbc -a /dev/zvol/rdsk/$ROOT_POOL/d $LOFIDEVICE
if [ "$?" != "0" ]
then echo "Ошибка lofiadm. Нажмите Enter для продолжения"
 read
 exit 1
fi

sudo /usr/sbin/zpool import -o cachefile=none -d /dev/lofi data
if [ "$?" != "0" ]
then sudo /usr/sbin/lofiadm -d $LOFIDEVICE
 echo "Ошибка zpool. Нажмите Enter для продолжения"
 read
 exit 1
fi
