#!/bin/sh
ROOT_POOL=rpool

sudo /usr/sbin/lofiadm -c aes-256-cbc -a /dev/zvol/rdsk/$ROOT_POOL/d /dev/lofi/100
if [ "$?" != "0" ]
then echo "Ошибка lofiadm. Нажмите Enter для продолжения"
 read
 exit 1
fi

sudo /usr/sbin/zpool import -o cachefile=none -d /dev/lofi data
if [ "$?" != "0" ]
then echo "Ошибка zpool. Нажмите Enter для продолжения"
 read
 exit 1
fi
