#!/bin/sh
if [ -z "$1" ] 
then
	echo "Usage: $0 <zvol size>"
	echo "For example: $0 50G"
	exit 1
fi

builtin grep
builtin chmod

OIFS=$IFS
IFS=' '
ROOT_POOL_ARR=(`/usr/sbin/mount|grep "^/ on "`)
IFS='/'
ROOT_POOL_ARR2=(${ROOT_POOL_ARR[2]})
ROOT_POOL=${ROOT_POOL_ARR2[0]}
IFS=$OIFS

/usr/sbin/zfs create -V $1 $ROOT_POOL/d && \
/usr/sbin/lofiadm -c aes-256-cbc -a /dev/zvol/rdsk/$ROOT_POOL/d /dev/lofi/100 && \
/usr/sbin/zpool create -o cachefile=none data /dev/lofi/100 && \
chmod a+w /usr/bin/crzt && \
/usr/bin/sed -i 's/^ROOT_POOL=.*/ROOT_POOL='$ROOT_POOL'/g' /usr/bin/crzt && \
chmod a-w /usr/bin/crzt && \
chmod a+w /usr/bin/crz && \
/usr/bin/sed -i 's/^ROOT_POOL=.*/ROOT_POOL='$ROOT_POOL'/g' /usr/bin/crz && \
chmod a-w /usr/bin/crz
