#!/bin/sh
sudo /usr/sbin/zpool export data 
if [ "$?" != "0" ]
then echo "Нажмите Enter для продолжения"
 read
fi

sudo /usr/sbin/lofiadm -d /dev/lofi/100
if [ "$?" != "0" ]
then echo "Нажмите Enter для продолжения"
 read
fi
